zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbAgentConfiguration/agentConfigurationService: node exists

--------------------------[Exception thrown]---------------------------
time:   2014-04-22-074157
type:   ML::Exception
pid:    8484; tid: 8484
what:   Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbAgentConfiguration/agentConfigurationService: node exists
stack:
00: 0x0x7f52d4f9fdb7 at __cxa_throw + 0x27 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so + 0xdb7/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so(__cxa_throw+0x27) [0x7f52d4f9fdb7]
01: 0x0x7f52d35a77c3 at Datacratic::ZookeeperConnection::checkRes(int, int&, char const*, char const*) + 0xe3 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x1097c3/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection8checkResEiRiPKcS3_+0xe3) [0x7f52d35a77c3]
02: 0x0x7f52d35a73c1 at Datacratic::ZookeeperConnection::createNode(std::string const&, std::string const&, bool, bool, bool, bool) + 0x441 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x1093c1/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection10createNodeERKSsS2_bbbb+0x441) [0x7f52d35a73c1]
03: 0x0x7f52d3560695 at Datacratic::ZookeeperConfigurationService::setUnique(std::string const&, Json::Value const&) + 0x285 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xc2695/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic29ZookeeperConfigurationService9setUniqueERKSsRKN4Json5ValueE+0x285) [0x7f52d3560695]
04: 0x0x7f52d354c004 at Datacratic::ServiceBase::registerServiceProvider(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) + 0x1c4 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xae004/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic11ServiceBase23registerServiceProviderERKSsRKSt6vectorISsSaISsEE+0x1c4) [0x7f52d354c004]
05: 0x0x7f52d48fe6db at RTBKIT::AgentConfigurationService::init() + 0x14b in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libagent_configuration.so + 0x8f6db/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libagent_configuration.so(_ZN6RTBKIT25AgentConfigurationService4initEv+0x14b) [0x7f52d48fe6db]
06: 0x0x4097ce at main + 0x3ee in build/x86_64/bin/agent_configuration_service_runner + 0x97cebuild/x86_64/bin/agent_configuration_service_runner(main+0x3ee) [0x4097ce]
07: 0x0x7f52d381d76d at __libc_start_main + 0xed in /lib/x86_64-linux-gnu/libc.so.6 + 0x2176d/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f52d381d76d]
08: 0x0x409a79 in build/x86_64/bin/agent_configuration_service_runner + 0x9a79build/x86_64/bin/agent_configuration_service_runner() [0x409a79]

terminate called after throwing an instance of 'ML::Exception'
  what():  Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbAgentConfiguration/agentConfigurationService: node exists
