connecting to Carbon at 127.0.0.1:2003 (localhost)
onStateLoaded: successfully loaded accounts
zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbBanker/masterBanker: node exists

--------------------------[Exception thrown]---------------------------
time:   2014-04-22-071237
type:   ML::Exception
pid:    5293; tid: 5293
what:   Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbBanker/masterBanker: node exists
stack:
00: 0x0x7f8f08f1fdb7 at __cxa_throw + 0x27 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so + 0xdb7/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so(__cxa_throw+0x27) [0x7f8f08f1fdb7]
01: 0x0x7f8f075317c3 at Datacratic::ZookeeperConnection::checkRes(int, int&, char const*, char const*) + 0xe3 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x1097c3/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection8checkResEiRiPKcS3_+0xe3) [0x7f8f075317c3]
02: 0x0x7f8f075313c1 at Datacratic::ZookeeperConnection::createNode(std::string const&, std::string const&, bool, bool, bool, bool) + 0x441 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x1093c1/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection10createNodeERKSsS2_bbbb+0x441) [0x7f8f075313c1]
03: 0x0x7f8f074ea695 at Datacratic::ZookeeperConfigurationService::setUnique(std::string const&, Json::Value const&) + 0x285 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xc2695/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic29ZookeeperConfigurationService9setUniqueERKSsRKN4Json5ValueE+0x285) [0x7f8f074ea695]
04: 0x0x7f8f074d6004 at Datacratic::ServiceBase::registerServiceProvider(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) + 0x1c4 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xae004/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic11ServiceBase23registerServiceProviderERKSsRKSt6vectorISsSaISsEE+0x1c4) [0x7f8f074d6004]
05: 0x0x7f8f08879c42 at RTBKIT::MasterBanker::init(std::shared_ptr<RTBKIT::BankerPersistence> const&) + 0x1d2 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libbanker.so + 0x60c42/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libbanker.so(_ZN6RTBKIT12MasterBanker4initERKSt10shared_ptrINS_17BankerPersistenceEE+0x1d2) [0x7f8f08879c42]
06: 0x0x40f0eb at main + 0x71b in build/x86_64/bin/banker_service_runner + 0xf0ebbuild/x86_64/bin/banker_service_runner(main+0x71b) [0x40f0eb]
07: 0x0x7f8f079f676d at __libc_start_main + 0xed in /lib/x86_64-linux-gnu/libc.so.6 + 0x2176d/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f8f079f676d]
08: 0x0x40f76d in build/x86_64/bin/banker_service_runner + 0xf76dbuild/x86_64/bin/banker_service_runner() [0x40f76d]

terminate called after throwing an instance of 'ML::Exception'
  what():  Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbBanker/masterBanker: node exists
