2014-04-22 07:25:40.724 ZMQ ./soa/service/zmq_endpoint.cc:447 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnecting to monitor/zeromq[0m
2014-04-22 07:25:40.725 ZMQ ./soa/service/zmq_endpoint.cc:494 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnected to tcp://ip-172-31-27-189.ec2.internal:24000[0m
2014-04-22 07:25:40.727 ZMQ ./soa/service/zmq_endpoint.cc:447 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnecting to monitor/zeromq[0m
2014-04-22 07:25:40.728 ZMQ ./soa/service/zmq_endpoint.cc:494 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnected to tcp://ip-172-31-27-189.ec2.internal:24000[0m
2014-04-22 07:25:40.729 ZMQ ./soa/service/zmq_endpoint.cc:447 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnecting to masterBanker/zeromq[0m
2014-04-22 07:25:40.731 ZMQ ./soa/service/zmq_endpoint.cc:494 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnected to tcp://ip-172-31-27-189.ec2.internal:22000[0m
augmentor frequency-cap-ex has connected
2014-04-22 07:25:40.756 ZMQ ./soa/service/zmq_endpoint.cc:447 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnecting to PostAuctionLoop/events[0m
agent fixed-price-agent-ex_6573 connected to router
2014-04-22 07:25:40.758 ZMQ ./soa/service/zmq_endpoint.cc:494 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnected to tcp://ip-172-31-27-189.ec2.internal:20000[0m
2014-04-22 07:25:40.759 ZMQ ./soa/service/zmq_endpoint.cc:447 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnecting to agentConfigurationService/listen[0m
2014-04-22 07:25:40.760 ZMQ ./soa/service/zmq_endpoint.cc:494 - bool Datacratic::ZmqNamedProxy::connect(const string&, Datacratic::ConnectionStyle) [1;31mconnected to tcp://ip-172-31-27-189.ec2.internal:19000[0m
got configuration message fixed-price-agent-ex_6573


agent fixed-price-agent-ex_6573 got new configuration

--------------------------[Exception thrown]---------------------------
time:   2014-04-22-072540
type:   ML::Exception
pid:    6666; tid: 6666
what:   couldn't bind to any port in range [12339,12340]
stack:
00: 0x0x7f832b773db7 at __cxa_throw + 0x27 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so + 0xdb7/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libexception_hook.so(__cxa_throw+0x27) [0x7f832b773db7]
01: 0x0x7f832980b092 at Datacratic::AcceptorT<Datacratic::SocketTransport>::listen(Datacratic::PortRange const&, std::string const&, Datacratic::PassiveEndpoint*, bool, int) + 0x1c2 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xa0092/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic9AcceptorTINS_15SocketTransportEE6listenERKNS_9PortRangeERKSsPNS_15PassiveEndpointEbi+0x1c2) [0x7f832980b092]
02: 0x0x7f832980ae0b at Datacratic::PassiveEndpoint::init(Datacratic::PortRange const&, std::string const&, int, bool, bool, int) + 0x4b in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x9fe0b/home/rtbkit/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic15PassiveEndpoint4initERKNS_9PortRangeERKSsibbi+0x4b) [0x7f832980ae0b]
03: 0x0x7f83192d2d80 at RTBKIT::MockExchangeConnector::start() + 0x60 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/../bin/libmock_exchange.so + 0x21d80/home/rtbkit/rtbkit/build/x86_64/bin/../bin/../bin/libmock_exchange.so(_ZN6RTBKIT21MockExchangeConnector5startEv+0x60) [0x7f83192d2d80]
04: 0x0x7f832b078dfd at RTBKIT::Router::startExchange(std::string const&, Json::Value const&) + 0x4d in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/librtb_router.so + 0x7bdfd/home/rtbkit/rtbkit/build/x86_64/bin/../bin/librtb_router.so(_ZN6RTBKIT6Router13startExchangeERKSsRKN4Json5ValueE+0x4d) [0x7f832b078dfd]
05: 0x0x7f832b079280 at RTBKIT::Router::startExchange(Json::Value const&) + 0x40 in /home/rtbkit/rtbkit/build/x86_64/bin/../bin/librtb_router.so + 0x7c280/home/rtbkit/rtbkit/build/x86_64/bin/../bin/librtb_router.so(_ZN6RTBKIT6Router13startExchangeERKN4Json5ValueE+0x40) [0x7f832b079280]
06: 0x0x421908 at RTBKIT::RouterRunner::start() + 0xb8 in build/x86_64/bin/router_runner + 0x21908build/x86_64/bin/router_runner(_ZN6RTBKIT12RouterRunner5startEv+0xb8) [0x421908]
07: 0x0x4201ba at main + 0x7a in build/x86_64/bin/router_runner + 0x201babuild/x86_64/bin/router_runner(main+0x7a) [0x4201ba]
08: 0x0x7f832a1da76d at __libc_start_main + 0xed in /lib/x86_64-linux-gnu/libc.so.6 + 0x2176d/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f832a1da76d]
09: 0x0x4208a9 in build/x86_64/bin/router_runner + 0x208a9build/x86_64/bin/router_runner() [0x4208a9]

terminate called after throwing an instance of 'ML::Exception'
  what():  couldn't bind to any port in range [12339,12340]
